#!/usr/bin/python3
def raise_exception():
    c = "2" + 2
